# Generated by Django 2.0 on 2019-10-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=150, verbose_name='昵称')),
                ('openid', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.URLField(verbose_name='头像')),
                ('gender', models.CharField(default='保密', max_length=2, verbose_name='性别')),
            ],
        ),
    ]
