# Generated by Django 2.0 on 2019-10-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielikecount',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MovieLikeCount',
        ),
    ]
