# Generated by Django 2.0 on 2019-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pythonuser',
            name='img',
            field=models.ImageField(default='static/upload/a.jpg', upload_to='upload/'),
        ),
    ]
