# Generated by Django 2.0 on 2019-09-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190916_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_down_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
