# Generated by Django 2.0 on 2019-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190917_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
