# Generated by Django 2.0 on 2019-09-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190918_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('movie_date', models.DateTimeField(auto_now_add=True)),
                ('user_comment_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Huifu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('movie_date', models.DateTimeField(auto_now_add=True)),
                ('user_huifu_content', models.CharField(max_length=50)),
                ('user_floor', models.IntegerField(default=1)),
                ('hf_user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('movie_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pythonuser',
            name='login_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
