# Generated by Django 2.0 on 2019-09-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190919_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_comment_content',
            field=models.CharField(max_length=255),
        ),
    ]
