# Generated by Django 2.0 on 2019-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190919_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
