# Generated by Django 2.0 on 2019-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonuser',
            name='all_price',
            field=models.FloatField(default=0),
        ),
    ]
