# Generated by Django 2.0 on 2019-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_pythonuser_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_price',
            field=models.FloatField(default=0),
        ),
    ]
