# Generated by Django 2.0 on 2019-09-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190920_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_introduction',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_screenwriter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_starring',
            field=models.TextField(blank=True, null=True),
        ),
    ]
