# Generated by Django 2.0 on 2019-09-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190920_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huifu',
            old_name='movie_date',
            new_name='hf_date',
        ),
        migrations.RemoveField(
            model_name='huifu',
            name='user_floor',
        ),
        migrations.AddField(
            model_name='huifu',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
