# Generated by Django 2.0 on 2019-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190924_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huifu',
            old_name='user_id',
            new_name='comment_user_id',
        ),
    ]
