# Generated by Django 2.0 on 2019-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190924_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huifu',
            name='hf_content',
            field=models.TextField(default=''),
        ),
    ]
