# Generated by Django 2.0 on 2019-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190925_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
